default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  

development:
  <<: *default
  database: rails-lamby-test-development

test:
  <<: *default
  database: rails-lamby-test-test

production:
  <<: *default
  url: <%= ENV["PG_URL"] %>
